language: python

env:
  global:
    - DOCKER_CACHE_DIR=${HOME}/.docker-cache
    - DOCKER_CACHE_FILE=${DOCKER_CACHE_DIR}/${DOCKER_IMAGE_NAME}.tar.gz
    - DOCKER_IMAGE_NAME=bable-cpp-compiler
    - DOCKER_CONTAINER_NAME=bable
    - CPP_BIN_DIR=tmp
    - CPP_SRC_DIR=platforms/linux
    - PYTHON_SRC_DIR=interfaces/python

cache:
  pip: true
  directories:
    - $DOCKER_CACHE_DIR

python:
  - 2.7
  - 3.6

sudo: required
services:
  - docker

install:
  - pip install tox-travis
  - pip install --upgrade -r interfaces/python/build_requirements.txt

script:
  - echo "OK"

before_deploy:
  - bash tools/cpp-compilation/load_docker.sh
  - docker-compose -f tools/cpp-compilation/docker-compose.yml up

deploy:
  skip_cleanup: true
  provider: script
  script: python tools/release.py --dry-run --build_sdist 0.0.1 ${PYTHON_SRC_DIR} ${CPP_BIN_DIR} # $TRAVIS_TAG
  on:
    branch: feat-add_ci
#    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
#
#  - provider: script
#    script: python tools/release.py --dry-run 0.0.1 ${PYTHON_SRC_DIR} ${CPP_BIN_DIR} # $TRAVIS_TAG
#    on:
#      branch: feat-add_ci
#  #    tags: true
#      condition: $TRAVIS_PYTHON_VERSION = "3.6"
