# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class CancelConnection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCancelConnection(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CancelConnection()
        x.Init(buf, n + offset)
        return x

    # CancelConnection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CancelConnectionStart(builder): builder.StartObject(0)
def CancelConnectionEnd(builder): return builder.EndObject()
