# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class DeviceRemoved(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDeviceRemoved(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceRemoved()
        x.Init(buf, n + offset)
        return x

    # DeviceRemoved
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceRemoved
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceRemoved
    def AddressType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def DeviceRemovedStart(builder): builder.StartObject(2)
def DeviceRemovedAddAddress(builder, address): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)
def DeviceRemovedAddAddressType(builder, addressType): builder.PrependUint8Slot(1, addressType, 0)
def DeviceRemovedEnd(builder): return builder.EndObject()
