# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class DeviceAdded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDeviceAdded(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceAdded()
        x.Init(buf, n + offset)
        return x

    # DeviceAdded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceAdded
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceAdded
    def AddressType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def DeviceAddedStart(builder): builder.StartObject(2)
def DeviceAddedAddAddress(builder, address): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)
def DeviceAddedAddAddressType(builder, addressType): builder.PrependUint8Slot(1, addressType, 0)
def DeviceAddedEnd(builder): return builder.EndObject()
