# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class Disconnect(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDisconnect(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Disconnect()
        x.Init(buf, n + offset)
        return x

    # Disconnect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Disconnect
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Disconnect
    def AddressType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 2

def DisconnectStart(builder): builder.StartObject(2)
def DisconnectAddAddress(builder, address): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)
def DisconnectAddAddressType(builder, addressType): builder.PrependUint8Slot(1, addressType, 2)
def DisconnectEnd(builder): return builder.EndObject()
