# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class Disconnect(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDisconnect(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Disconnect()
        x.Init(buf, n + offset)
        return x

    # Disconnect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Disconnect
    def ConnectionHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def DisconnectStart(builder): builder.StartObject(1)
def DisconnectAddConnectionHandle(builder, connectionHandle): builder.PrependUint16Slot(0, connectionHandle, 0)
def DisconnectEnd(builder): return builder.EndObject()
