# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class ErrorResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsErrorResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ErrorResponse()
        x.Init(buf, n + offset)
        return x

    # ErrorResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ErrorResponse
    def Opcode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ErrorResponse
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def ErrorResponseStart(builder): builder.StartObject(2)
def ErrorResponseAddOpcode(builder, opcode): builder.PrependUint8Slot(0, opcode, 0)
def ErrorResponseAddHandle(builder, handle): builder.PrependUint16Slot(1, handle, 0)
def ErrorResponseEnd(builder): return builder.EndObject()
