# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class Exit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExit(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Exit()
        x.Init(buf, n + offset)
        return x

    # Exit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ExitStart(builder): builder.StartObject(0)
def ExitEnd(builder): return builder.EndObject()
