# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class GetConnectedDevices(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetConnectedDevices(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetConnectedDevices()
        x.Init(buf, n + offset)
        return x

    # GetConnectedDevices
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetConnectedDevices
    def Devices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GetConnectedDevices
    def DevicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def GetConnectedDevicesStart(builder): builder.StartObject(1)
def GetConnectedDevicesAddDevices(builder, devices): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(devices), 0)
def GetConnectedDevicesStartDevicesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GetConnectedDevicesEnd(builder): return builder.EndObject()
