# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

class Payload(object):
    NONE = 0
    CancelConnection = 1
    Connect = 2
    Disconnect = 3
    GetConnectedDevices = 4
    GetControllersIds = 5
    GetControllerInfo = 6
    GetControllersList = 7
    ProbeCharacteristics = 8
    ProbeServices = 9
    Read = 10
    SetConnectable = 11
    SetDiscoverable = 12
    SetGATTTable = 13
    SetPowered = 14
    StartScan = 15
    StopScan = 16
    Write = 17
    WriteWithoutResponse = 18
    ControllerAdded = 19
    ControllerRemoved = 20
    DeviceConnected = 21
    DeviceDisconnected = 22
    DeviceFound = 23
    NotificationReceived = 24
    BaBLEError = 25
    Exit = 26
    Ready = 27

