# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

class Payload(object):
    NONE = 0
    AddDevice = 1
    Disconnect = 2
    GetConnectedDevices = 3
    GetControllersIds = 4
    GetControllerInfo = 5
    GetControllersList = 6
    GetMGMTInfo = 7
    ProbeCharacteristics = 8
    ProbeServices = 9
    Read = 10
    RemoveDevice = 11
    SetConnectable = 12
    SetDiscoverable = 13
    SetPowered = 14
    StartScan = 15
    StopScan = 16
    Write = 17
    WriteWithoutResponse = 18
    ControllerAdded = 19
    ControllerRemoved = 20
    DeviceAdded = 21
    DeviceRemoved = 22
    DeviceConnected = 23
    DeviceDisconnected = 24
    DeviceFound = 25
    Discovering = 26
    NotificationReceived = 27
    BaBLEError = 28
    ErrorResponse = 29
    Exit = 30
    Ready = 31

