# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

class Payload(object):
    NONE = 0
    CancelConnection = 1
    Connect = 2
    Disconnect = 3
    GetConnectedDevices = 4
    GetControllersIds = 5
    GetControllerInfo = 6
    GetControllersList = 7
    ProbeCharacteristics = 8
    ProbeServices = 9
    ReadCentral = 10
    ReadPeripheral = 11
    SetAdvertising = 12
    SetConnectable = 13
    SetDiscoverable = 14
    SetGATTTable = 15
    SetPowered = 16
    StartScan = 17
    StopScan = 18
    WriteCentral = 19
    WritePeripheral = 20
    WriteWithoutResponseCentral = 21
    WriteWithoutResponsePeripheral = 22
    ControllerAdded = 23
    ControllerRemoved = 24
    DeviceConnected = 25
    DeviceDisconnected = 26
    DeviceFound = 27
    NotificationReceived = 28
    BaBLEError = 29
    Exit = 30
    Ready = 31

