# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class RemoveDevice(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRemoveDevice(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoveDevice()
        x.Init(buf, n + offset)
        return x

    # RemoveDevice
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoveDevice
    def Address(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RemoveDevice
    def AddressType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 2

def RemoveDeviceStart(builder): builder.StartObject(2)
def RemoveDeviceAddAddress(builder, address): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(address), 0)
def RemoveDeviceAddAddressType(builder, addressType): builder.PrependUint8Slot(1, addressType, 2)
def RemoveDeviceEnd(builder): return builder.EndObject()
