# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class SetConnectable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSetConnectable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetConnectable()
        x.Init(buf, n + offset)
        return x

    # SetConnectable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetConnectable
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetConnectableStart(builder): builder.StartObject(1)
def SetConnectableAddState(builder, state): builder.PrependBoolSlot(0, state, 0)
def SetConnectableEnd(builder): return builder.EndObject()
