# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class SetCharacteristics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSetCharacteristics(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetCharacteristics()
        x.Init(buf, n + offset)
        return x

    # SetCharacteristics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetCharacteristics
    def Characteristics(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Characteristic import Characteristic
            obj = Characteristic()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SetCharacteristics
    def CharacteristicsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SetCharacteristicsStart(builder): builder.StartObject(1)
def SetCharacteristicsAddCharacteristics(builder, characteristics): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(characteristics), 0)
def SetCharacteristicsStartCharacteristicsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SetCharacteristicsEnd(builder): return builder.EndObject()
