# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class SetServices(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSetServices(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetServices()
        x.Init(buf, n + offset)
        return x

    # SetServices
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetServices
    def Services(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Service import Service
            obj = Service()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SetServices
    def ServicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SetServicesStart(builder): builder.StartObject(1)
def SetServicesAddServices(builder, services): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(services), 0)
def SetServicesStartServicesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SetServicesEnd(builder): return builder.EndObject()
