# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class GetControllerInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetControllerInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetControllerInfo()
        x.Init(buf, n + offset)
        return x

    # GetControllerInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetControllerInfo
    def ControllerInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Controller import Controller
            obj = Controller()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def GetControllerInfoStart(builder): builder.StartObject(1)
def GetControllerInfoAddControllerInfo(builder, controllerInfo): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(controllerInfo), 0)
def GetControllerInfoEnd(builder): return builder.EndObject()
