# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class GetMGMTInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGetMGMTInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetMGMTInfo()
        x.Init(buf, n + offset)
        return x

    # GetMGMTInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetMGMTInfo
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GetMGMTInfo
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def GetMGMTInfoStart(builder): builder.StartObject(2)
def GetMGMTInfoAddVersion(builder, version): builder.PrependUint8Slot(0, version, 0)
def GetMGMTInfoAddRevision(builder, revision): builder.PrependUint16Slot(1, revision, 0)
def GetMGMTInfoEnd(builder): return builder.EndObject()
