# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class Ready(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReady(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Ready()
        x.Init(buf, n + offset)
        return x

    # Ready
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ReadyStart(builder): builder.StartObject(0)
def ReadyEnd(builder): return builder.EndObject()
