# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

import flatbuffers

class SetDiscoverable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSetDiscoverable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetDiscoverable()
        x.Init(buf, n + offset)
        return x

    # SetDiscoverable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetDiscoverable
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SetDiscoverable
    def Timeout(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def SetDiscoverableStart(builder): builder.StartObject(2)
def SetDiscoverableAddState(builder, state): builder.PrependBoolSlot(0, state, 0)
def SetDiscoverableAddTimeout(builder, timeout): builder.PrependUint16Slot(1, timeout, 0)
def SetDiscoverableEnd(builder): return builder.EndObject()
