# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BaBLE

class StatusCode(object):
    Success = 0
    SocketError = 1
    NotFound = 2
    WrongFormat = 3
    InvalidCommand = 4
    Unknown = 5
    Rejected = 6
    Denied = 7
    Cancelled = 8
    NotPowered = 9
    Failed = 10
    NotConnected = 11

