version: '3'
services:
  x86_64:
    image: ${DOCKER_IMAGE_NAME}
    working_dir: /build
    command: bash /tools/compile.sh x86_64 /src/${CPP_SRC_DIR} /src/${CPP_BIN_DIR}
    volumes:
      - ../..:/src
      - .:/tools

  i686:
      image: ${DOCKER_IMAGE_NAME}
      working_dir: /build
      command: bash /tools/compile.sh i686 /src/${CPP_SRC_DIR} /src/${CPP_BIN_DIR}
      volumes:
        - ../..:/src
        - .:/tools

  armv7l:
      image: ${DOCKER_IMAGE_NAME}
      working_dir: /build
      command: bash /tools/compile.sh armv7l /src/${CPP_SRC_DIR} /src/${CPP_BIN_DIR}
      volumes:
        - ../..:/src
        - .:/tools
